name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Run tests (release)
        run: cargo test --verbose --release

  fmt_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Formatting
        run: cargo fmt --check
      - name: Linting
        run: cargo clippy --verbose

  example_grep:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ext: [bq, vbq, cbq]
    steps:
      - uses: actions/checkout@v3
      - name: run example ${matrix.ext}
        run: cargo run --release --example grep ./data/subset.${matrix.ext}

  example_range:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ext: [bq, vbq, cbq]
    steps:
      - uses: actions/checkout@v3
      - name: run example ${matrix.ext}
        run: cargo run --release --example parallel_range -- ./data/subset.${matrix.ext} 4 30 200

  example_write:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ext: [bq, vbq, cbq]
    steps:
      - uses: actions/checkout@v3
      - name: run example (single) ${matrix.ext}
        run: cargo run --release --example write -- ./data/subset_R1.fastq.gz -o ./output.${matrix.ext}
      - name: run example (paired) ${matrix.ext}
        run: cargo run --release --example write -- ./data/subset_R1.fastq.gz ./data/subset_R2.fastq.gz -o ./output.${matrix.ext}

  example_read:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ext: [bq, vbq, cbq]
    steps:
      - uses: actions/checkout@v3
      - name: run example ${matrix.ext}
        run: cargo run --release --example read -- ./data/subset.${matrix.ext}
